---

name: bosca
services:
  bao-setup:
    image: openbao/openbao:latest
    environment:
      GITHUB_REPOSITORY: $GITHUB_REPOSITORY
      SETUP_COMMAND: bao
      BAO_TOKEN: BatteryStaple
      BAO_ADDR: http://bao-server:8200
    volumes:
      - ./setup-server:/mnt/setup-server
    entrypoint: /mnt/setup-server
    depends_on:
      bao-server:
        condition: service_healthy

  bao-server:
    cap_add:
      - IPC_LOCK
    image: openbao/openbao:latest
    environment:
      BAO_DEV_ROOT_TOKEN_ID: BatteryStaple
    ports:
      - 127.0.0.1:8200:8200
    healthcheck:
      test: ["CMD", "/usr/bin/nc", "-z", "127.0.0.1", "8200"]
      interval: 1s
      timeout: 1s
      retries: 5
