---

name: Self-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  integration:
    name: Integration test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run self
        id: ssh_cert
        uses: ./
        with:
          vault_server: https://vault.arrakis.se:8200
          oidc_backend_path: github-oidc
          oidc_role: cert-action-user
          ssh_backend_path: arrakis/ssh2
          ssh_role: cert-action-cert

      - name: Examine generated certificate
        run: ssh-keygen -L -f "${{ steps.ssh_cert.outputs.cert_path }}"

      - name: Run self, with audience conf
        id: ssh_cert_aud
        uses: ./
        with:
          vault_server: https://vault.arrakis.se:8200
          jwt_audience: a-test-audience
          oidc_backend_path: github-oidc
          oidc_role: cert-action-at-user
          ssh_backend_path: arrakis/ssh2
          ssh_role: cert-action-at-cert

      - name: Examine second generated certificate
        run: ssh-keygen -L -f "${{ steps.ssh_cert_aud.outputs.cert_path }}"
